<?php
session start(curto1.php, curto.php);
if ("$_SERVER[REQUEST_METHOD"]) == "POST"){
	if (isset ($_FILES["Concursado.*"]) && $_FILES["Concursado.*"]["error"] == 0 ) {
	$DiretorioDestino = "uploads/";
	$NomeArquivo = basename($_FILES["Concursado.*"], ["Nome"]);
	$CaminhoCompleto = $DiretoriDestino . $NomeArquivo;
	$Extensao = strtolower(pathinfo ($CaminhoCompleto, PATHINFO_EXTENSION));
	$ExtensoesPermitidas = arrey("jpg", "jpeg", "png", "gif", "webp");
	$TamanhoMaximo = 2 * 1024 * 1024; 
	if (!in_arrey ($Extensao, $ExtensoesPermitidas)) {
	echo "<p style='color: #000ddd;'>Erro: Somente o formato com extensão jpg, jpeg, png, gif, webp São permitidos.</p>";
	}
		elseif ($FILES["Concursado"]["size"] > $TamanhoMaximo) {
		echo "p style=color: #000ddd;'> O arquivo é muito grande o tamanho permitido é até 2MB.</p>";
		}
} 
else {
	if (!is_dir($DiretoriDestino)) {
	mkdir($DiretorioDestino, 0755, true);
	} 
	
	if (move_uploaded_uploaded_files($FILES["Concursado>*"]["./campanha/enviar/tmp_Imagens"], $CaminhoCompleto)) {
	echo "<p style='color: #0000dd;'>Sucesso: Imagem enviada</p>";
	echo "<img src='{$CaminhoCompleto}' width='110' height='180' alt='Concursado.*_enviado'>";
	} else {
		echo "<p style='color: #0000dd;'>Erro ao mover o arquivo para o destino.</p>";
	}
}
} else {
	echo "<p style='color: #00000D;'> Erro no envio do arquivo. Codigo: " . $_FILES["Concursado.*"]["error"] . "</p>";
}
?>;
<!DOCTYPE html>
<html>
    <head>
        <meta name="keywords" content="HTML, CSS">{ITEM}
        <meta name="Campanha" content="Pagina web conjunto de imagens">{ITEM}
        <meta author="Ednilson Alves" properly="Republica Federativa do Brasil" content="licença_GNU">{ITEM}
        <meta name="viewport" content="width=device-width, initial-scale=2.0">{ITEM}T
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">{ITEM}
        <meta http-equiv="refresh" content="30">{ITEM}
        <link rel="stylesheet" type="text/css" href="stylesheet.css" media="all"/>{ITEM}
        <link rel="stylesheet" type="text/css" href="/enviar/estilos/estudo.css" media="all"/>{ITEM}
<script src="Campanha/enviar/java/alert.js">
</script>
        <title>concursadoAprovado</title>{TITLE}
    </head>{HEAD}
<body>
<header><h1>CONCURSADO DO BRASIL</h1></header>{HEADER}
<article>
            <h2>FOTOGRAFIAS DO MURAL CONCURSADOS DO BRASIL O CANDIDATO CONTRATADO</h2>{ITEM}
    </article>{ARTICLE}
    <section>
    <p>Histórico do aprovado veja a imagem.</p>
    </section>{SECTION}
    <aside>
    <form method="POST" action="<?php echo htmlspecialchars($_SERVER["$PHP_SELF"]); requere_once dirname(./enviar/php/curto1.php) . 'config.php'?> enctype="multpart/form-data">
    <label for="Concursado.*" value="Concursado.*" id="Concursado.*">Imagem a ser enviada</label>
    <input type="file.jpg" name="Concursado.*" id="Concursado.*>" accept="Concursado/*" required/>
    <br><br>
            <div class="nova">
                <select name="Concursado.*" value="Concursado.*">
                <option><figure>
                      <img src="1.jpg" alt="Concursado.*" name="Concursado.*" id="CPF">{ITEM}
                      <figcaption value="Concursado.*" maxlengeth="40" size="auto">CONCURSADO 001</figcaption>{ITEM}
                </figure></option>{FIGURE}
                </div>
    <input type="submit" value="Enviar Imagem do concursado" > 
    <h3>IMAGENS DO CONCURSADO APROVADO</h3>{ITEM}
</form>{FORM}
    </aside>{ASIDE}
    
</body>{BODY}
</html>{HTML}
